import type {
    Zone,
    Woreda,
    School,
    Staff,
    Asset,
    BudgetAllocation,
    KPIData
} from '../types';

// ====================================
// ZONES
// ====================================

export const mockZones: Zone[] = [
    {
        id: 'zone-001',
        name: 'Mekelle',
        nameAmharic: 'መቐለ',
        code: 'MKL',
        description: 'Central zone including Mekelle city',
        totalWoredas: 8,
        totalSchools: 245,
        totalStudents: 125000,
        totalTeachers: 4200,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'zone-002',
        name: 'Adigrat',
        nameAmharic: 'ዓዲግራት',
        code: 'ADG',
        description: 'Eastern zone',
        totalWoredas: 6,
        totalSchools: 180,
        totalStudents: 85000,
        totalTeachers: 2900,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-10'),
    },
    {
        id: 'zone-003',
        name: 'Axum',
        nameAmharic: 'ኣኽሱም',
        code: 'AXM',
        description: 'Central zone with historical significance',
        totalWoredas: 7,
        totalSchools: 165,
        totalStudents: 78000,
        totalTeachers: 2650,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-12'),
    },
    {
        id: 'zone-004',
        name: 'Shire',
        nameAmharic: 'ሽረ',
        code: 'SHR',
        description: 'North-western zone',
        totalWoredas: 5,
        totalSchools: 142,
        totalStudents: 62000,
        totalTeachers: 2100,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-08'),
    },
    {
        id: 'zone-005',
        name: 'Wukro',
        nameAmharic: 'ዉቕሮ',
        code: 'WKR',
        description: 'Eastern industrial zone',
        totalWoredas: 4,
        totalSchools: 98,
        totalStudents: 45000,
        totalTeachers: 1520,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-05'),
    },
    {
        id: 'zone-006',
        name: 'Adwa',
        nameAmharic: 'ዓድዋ',
        code: 'ADW',
        description: 'Historical northern zone',
        totalWoredas: 5,
        totalSchools: 118,
        totalStudents: 52000,
        totalTeachers: 1780,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-14'),
    },
];

// ====================================
// WOREDAS
// ====================================

export const mockWoredas: Woreda[] = [
    // Mekelle Zone Woredas
    {
        id: 'woreda-001',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Ayder',
        nameAmharic: 'ዓይደር',
        code: 'AYD',
        description: 'Central woreda of Mekelle',
        totalSchools: 35,
        totalStudents: 18000,
        totalTeachers: 620,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'woreda-002',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Hawelti',
        nameAmharic: 'ሓወልቲ',
        code: 'HWT',
        description: 'Eastern woreda of Mekelle',
        totalSchools: 28,
        totalStudents: 14500,
        totalTeachers: 490,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-14'),
    },
    {
        id: 'woreda-003',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Kedamay Weyane',
        nameAmharic: 'ቀዳማይ ወያነ',
        code: 'KDW',
        description: 'Southern woreda of Mekelle',
        totalSchools: 32,
        totalStudents: 16200,
        totalTeachers: 545,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-13'),
    },
    {
        id: 'woreda-004',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Hadnet',
        nameAmharic: 'ሓድነት',
        code: 'HDN',
        description: 'Western woreda of Mekelle',
        totalSchools: 25,
        totalStudents: 12800,
        totalTeachers: 430,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-12'),
    },
    // Adigrat Zone Woredas
    {
        id: 'woreda-005',
        zoneId: 'zone-002',
        zoneName: 'Adigrat',
        name: 'Ganta Afeshum',
        nameAmharic: 'ጋንታ ዓፈሹም',
        code: 'GAF',
        description: 'Central woreda of Adigrat zone',
        totalSchools: 42,
        totalStudents: 21000,
        totalTeachers: 715,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-10'),
    },
    {
        id: 'woreda-006',
        zoneId: 'zone-002',
        zoneName: 'Adigrat',
        name: 'Gulomahda',
        nameAmharic: 'ጉሎማሕዳ',
        code: 'GLM',
        description: 'Northern woreda of Adigrat zone',
        totalSchools: 28,
        totalStudents: 13500,
        totalTeachers: 460,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-09'),
    },
];

// ====================================
// SCHOOLS
// ====================================

export const mockSchools: School[] = [
    {
        id: 'school-001',
        woredaId: 'woreda-001',
        woredaName: 'Ayder',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Ayder Primary School',
        nameAmharic: 'ዓይደር አንደኛ ደረጃ ትምህርት ቤት',
        code: 'AYD-PRI-001',
        type: 'primary',
        ownership: 'government',
        address: 'Ayder, Mekelle',
        phone: '+251-34-123-4567',
        email: 'ayderprimary@edu.gov.et',
        principalName: 'Gebremichael Tesfay',
        establishedYear: 1985,
        totalStudents: 850,
        totalTeachers: 32,
        totalStaff: 45,
        latitude: 13.5170,
        longitude: 39.4750,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'school-002',
        woredaId: 'woreda-001',
        woredaName: 'Ayder',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Ayder Secondary School',
        nameAmharic: 'ዓይደር ሁለተኛ ደረጃ ትምህርት ቤት',
        code: 'AYD-SEC-001',
        type: 'secondary',
        ownership: 'government',
        address: 'Ayder, Mekelle',
        phone: '+251-34-123-4568',
        email: 'aydersecondary@edu.gov.et',
        principalName: 'Hailay Berhe',
        establishedYear: 1992,
        totalStudents: 1200,
        totalTeachers: 48,
        totalStaff: 62,
        latitude: 13.5180,
        longitude: 39.4760,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-14'),
    },
    {
        id: 'school-003',
        woredaId: 'woreda-001',
        woredaName: 'Ayder',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Mekelle Preparatory School',
        nameAmharic: 'መቐለ መሰናዶ ትምህርት ቤት',
        code: 'MKL-PRP-001',
        type: 'preparatory',
        ownership: 'government',
        address: 'Ayder, Mekelle',
        phone: '+251-34-123-4569',
        email: 'mekelleprep@edu.gov.et',
        principalName: 'Assefa Gebremedhin',
        establishedYear: 1998,
        totalStudents: 2100,
        totalTeachers: 78,
        totalStaff: 95,
        latitude: 13.5190,
        longitude: 39.4740,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-13'),
    },
    {
        id: 'school-004',
        woredaId: 'woreda-002',
        woredaName: 'Hawelti',
        zoneId: 'zone-001',
        zoneName: 'Mekelle',
        name: 'Hawelti Primary School',
        nameAmharic: 'ሓወልቲ አንደኛ ደረጃ ትምህርት ቤት',
        code: 'HWT-PRI-001',
        type: 'primary',
        ownership: 'government',
        address: 'Hawelti, Mekelle',
        phone: '+251-34-234-5678',
        email: 'haweltiprimary@edu.gov.et',
        principalName: 'Mulu Hailu',
        establishedYear: 1988,
        totalStudents: 720,
        totalTeachers: 28,
        totalStaff: 38,
        latitude: 13.4950,
        longitude: 39.4820,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-12'),
    },
    {
        id: 'school-005',
        woredaId: 'woreda-005',
        woredaName: 'Ganta Afeshum',
        zoneId: 'zone-002',
        zoneName: 'Adigrat',
        name: 'Ganta Afeshum Primary School',
        nameAmharic: 'ጋንታ ዓፈሹም አንደኛ ደረጃ ትምህርት ቤት',
        code: 'GAF-PRI-001',
        type: 'primary',
        ownership: 'government',
        address: 'Ganta Afeshum, Adigrat',
        phone: '+251-34-345-6789',
        email: 'gantaafeshum@edu.gov.et',
        principalName: 'Bereket Tadesse',
        establishedYear: 1990,
        totalStudents: 680,
        totalTeachers: 26,
        totalStaff: 35,
        latitude: 14.2800,
        longitude: 39.4600,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-10'),
    },
];

// ====================================
// STAFF
// ====================================

export const mockStaff: Staff[] = [
    {
        id: 'staff-001',
        schoolId: 'school-001',
        schoolName: 'Ayder Primary School',
        woredaId: 'woreda-001',
        zoneId: 'zone-001',
        employeeId: 'EMP-2020-001',
        firstName: 'Kidist',
        lastName: 'Gebremichael',
        fatherName: 'Hailu',
        gender: 'female',
        dateOfBirth: new Date('1985-03-15'),
        phone: '+251-91-123-4567',
        email: 'kidist.g@edu.gov.et',
        position: 'teacher',
        subject: 'Mathematics',
        educationLevel: 'degree',
        qualification: 'BSc Mathematics',
        hireDate: new Date('2010-09-01'),
        salary: 8500,
        yearsOfExperience: 14,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'staff-002',
        schoolId: 'school-001',
        schoolName: 'Ayder Primary School',
        woredaId: 'woreda-001',
        zoneId: 'zone-001',
        employeeId: 'EMP-2018-002',
        firstName: 'Yohannes',
        lastName: 'Berhe',
        fatherName: 'Tesfay',
        gender: 'male',
        dateOfBirth: new Date('1980-07-22'),
        phone: '+251-91-234-5678',
        email: 'yohannes.b@edu.gov.et',
        position: 'principal',
        educationLevel: 'masters',
        qualification: 'MEd Educational Leadership',
        hireDate: new Date('2005-09-01'),
        salary: 12500,
        yearsOfExperience: 19,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-14'),
    },
    {
        id: 'staff-003',
        schoolId: 'school-002',
        schoolName: 'Ayder Secondary School',
        woredaId: 'woreda-001',
        zoneId: 'zone-001',
        employeeId: 'EMP-2015-003',
        firstName: 'Almaz',
        lastName: 'Tesfaye',
        fatherName: 'Gebru',
        gender: 'female',
        dateOfBirth: new Date('1988-11-08'),
        phone: '+251-91-345-6789',
        email: 'almaz.t@edu.gov.et',
        position: 'teacher',
        subject: 'English',
        educationLevel: 'degree',
        qualification: 'BA English',
        hireDate: new Date('2015-09-01'),
        salary: 7500,
        yearsOfExperience: 9,
        status: 'active',
        createdAt: new Date('2020-01-01'),
        updatedAt: new Date('2024-01-13'),
    },
];

// ====================================
// ASSETS
// ====================================

export const mockAssets: Asset[] = [
    {
        id: 'asset-001',
        assetCode: 'AST-2024-001',
        name: 'Desktop Computer',
        category: 'electronics',
        quantity: 25,
        unitValue: 15000,
        totalValue: 375000,
        condition: 'good',
        location: 'Ayder Primary School - Computer Lab',
        schoolId: 'school-001',
        woredaId: 'woreda-001',
        zoneId: 'zone-001',
        tenantType: 'school',
        status: 'active',
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'asset-002',
        assetCode: 'AST-2024-002',
        name: 'Student Desks',
        category: 'furniture',
        quantity: 200,
        unitValue: 800,
        totalValue: 160000,
        condition: 'fair',
        location: 'Ayder Primary School',
        schoolId: 'school-001',
        woredaId: 'woreda-001',
        zoneId: 'zone-001',
        tenantType: 'school',
        status: 'active',
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'asset-003',
        assetCode: 'AST-2024-003',
        name: 'Projector',
        category: 'electronics',
        quantity: 5,
        unitValue: 25000,
        totalValue: 125000,
        condition: 'new',
        location: 'Ayder Secondary School',
        schoolId: 'school-002',
        woredaId: 'woreda-001',
        zoneId: 'zone-001',
        tenantType: 'school',
        status: 'active',
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
    {
        id: 'asset-004',
        assetCode: 'AST-2024-004',
        name: 'Laboratory Equipment Set',
        category: 'equipment',
        quantity: 3,
        unitValue: 50000,
        totalValue: 150000,
        condition: 'good',
        location: 'Mekelle Preparatory School',
        schoolId: 'school-003',
        woredaId: 'woreda-001',
        zoneId: 'zone-001',
        tenantType: 'school',
        status: 'active',
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-15'),
    },
];

// ====================================
// KPI DATA
// ====================================

export const bureauKPIs: KPIData[] = [
    {
        label: 'Total Zones',
        value: 6,
        previousValue: 6,
        change: 0,
        changePercent: 0,
        trend: 'stable',
        icon: 'Map',
    },
    {
        label: 'Total Woredas',
        value: 35,
        previousValue: 34,
        change: 1,
        changePercent: 2.9,
        trend: 'up',
        icon: 'LocationCity',
    },
    {
        label: 'Total Schools',
        value: 948,
        previousValue: 912,
        change: 36,
        changePercent: 3.9,
        trend: 'up',
        icon: 'School',
    },
    {
        label: 'Total Students',
        value: 447000,
        previousValue: 428000,
        change: 19000,
        changePercent: 4.4,
        trend: 'up',
        icon: 'People',
    },
    {
        label: 'Total Teachers',
        value: 15150,
        previousValue: 14200,
        change: 950,
        changePercent: 6.7,
        trend: 'up',
        icon: 'Badge',
    },
    {
        label: 'Student-Teacher Ratio',
        value: 29.5,
        previousValue: 30.1,
        change: -0.6,
        changePercent: -2.0,
        trend: 'down',
        icon: 'Groups',
    },
];

export const zoneKPIs: KPIData[] = [
    {
        label: 'Woredas',
        value: 8,
        previousValue: 8,
        trend: 'stable',
        icon: 'LocationCity',
    },
    {
        label: 'Schools',
        value: 245,
        previousValue: 238,
        change: 7,
        changePercent: 2.9,
        trend: 'up',
        icon: 'School',
    },
    {
        label: 'Students',
        value: 125000,
        previousValue: 120000,
        change: 5000,
        changePercent: 4.2,
        trend: 'up',
        icon: 'People',
    },
    {
        label: 'Teachers',
        value: 4200,
        previousValue: 4050,
        change: 150,
        changePercent: 3.7,
        trend: 'up',
        icon: 'Badge',
    },
];

// ====================================
// DATA SERVICE
// ====================================

export const mockDataService = {
    // Zones
    getZones: () => Promise.resolve(mockZones),
    getZoneById: (id: string) => Promise.resolve(mockZones.find(z => z.id === id)),

    // Woredas
    getWoredas: (zoneId?: string) => {
        const filtered = zoneId
            ? mockWoredas.filter(w => w.zoneId === zoneId)
            : mockWoredas;
        return Promise.resolve(filtered);
    },
    getWoredaById: (id: string) => Promise.resolve(mockWoredas.find(w => w.id === id)),

    // Schools
    getSchools: (woredaId?: string, zoneId?: string) => {
        let filtered = mockSchools;
        if (woredaId) filtered = filtered.filter(s => s.woredaId === woredaId);
        if (zoneId) filtered = filtered.filter(s => s.zoneId === zoneId);
        return Promise.resolve(filtered);
    },
    getSchoolById: (id: string) => Promise.resolve(mockSchools.find(s => s.id === id)),

    // Staff
    getStaff: (schoolId?: string) => {
        const filtered = schoolId
            ? mockStaff.filter(s => s.schoolId === schoolId)
            : mockStaff;
        return Promise.resolve(filtered);
    },
    getStaffById: (id: string) => Promise.resolve(mockStaff.find(s => s.id === id)),

    // KPIs
    getBureauKPIs: () => Promise.resolve(bureauKPIs),
    getZoneKPIs: () => Promise.resolve(zoneKPIs),
};

export default mockDataService;
